export const stateOptions = [
  // México
  { label: 'Aguascalientes', value: 'AGS' },
  { label: 'Baja California', value: 'BC' },
  { label: 'Baja California Sur', value: 'BCS' },
  { label: 'Campeche', value: 'CAMP' },
  { label: 'Chiapas', value: 'CHIS' },
  { label: 'Chihuahua', value: 'CHIH' },
  { label: 'Ciudad de México', value: 'CDMX' },
  { label: 'Coahuila', value: 'COAH' },
  { label: 'Colima', value: 'COL' },
  { label: 'Durango', value: 'DGO' },
  { label: 'Guanajuato', value: 'GTO' },
  { label: 'Guerrero', value: 'GRO' },
  { label: 'Hidalgo', value: 'HGO' },
  { label: 'Jalisco', value: 'JAL' },
  { label: 'Estado de México', value: 'MEX' },
  { label: 'Michoacán', value: 'MICH' },
  { label: 'Morelos', value: 'MOR' },
  { label: 'Nayarit', value: 'NAY' },
  { label: 'Nuevo León', value: 'NL' },
  { label: 'Oaxaca', value: 'OAX' },
  { label: 'Puebla', value: 'PUE' },
  { label: 'Querétaro', value: 'QRO' },
  { label: 'Quintana Roo', value: 'QROO' },
  { label: 'San Luis Potosí', value: 'SLP' },
  { label: 'Sinaloa', value: 'SIN' },
  { label: 'Sonora', value: 'SON' },
  { label: 'Tabasco', value: 'TAB' },
  { label: 'Tamaulipas', value: 'TAMPS' },
  { label: 'Tlaxcala', value: 'TLAX' },
  { label: 'Veracruz', value: 'VER' },
  { label: 'Yucatán', value: 'YUC' },
  { label: 'Zacatecas', value: 'ZAC' },

  // Argentina
  { label: 'Buenos Aires', value: 'BA' },
  { label: 'Catamarca', value: 'CT' },
  { label: 'Chaco', value: 'CC' },
  { label: 'Chubut', value: 'CH' },
  { label: 'Córdoba', value: 'CB' },
  { label: 'Corrientes', value: 'CR' },
  { label: 'Entre Ríos', value: 'ER' },
  { label: 'Formosa', value: 'FO' },
  { label: 'Jujuy', value: 'JY' },
  { label: 'La Pampa', value: 'LP' },
  { label: 'La Rioja', value: 'LR-AR' },
  { label: 'Mendoza', value: 'MZ' },
  { label: 'Misiones', value: 'MI' },
  { label: 'Neuquén', value: 'NQ' },
  { label: 'Río Negro', value: 'RN' },
  { label: 'Salta', value: 'SA' },
  { label: 'San Juan', value: 'SJ' },
  { label: 'San Luis', value: 'SL' },
  { label: 'Santa Cruz', value: 'SC' },
  { label: 'Santa Fe', value: 'SF' },
  { label: 'Santiago del Estero', value: 'SE' },
  { label: 'Tierra del Fuego', value: 'TF' },
  { label: 'Tucumán', value: 'TU' },

  // Colombia
  { label: 'Amazonas', value: 'AMA' },
  { label: 'Antioquia', value: 'ANT' },
  { label: 'Arauca', value: 'ARA' },
  { label: 'Atlántico', value: 'ATL' },
  { label: 'Bogotá D.C.', value: 'BOG' },
  { label: 'Bolívar', value: 'BOL' },
  { label: 'Boyacá', value: 'BOY' },
  { label: 'Caldas', value: 'CAL' },
  { label: 'Caquetá', value: 'CAQ' },
  { label: 'Casanare', value: 'CAS' },
  { label: 'Cauca', value: 'CAU' },
  { label: 'Cesar', value: 'CES' },
  { label: 'Chocó', value: 'CHO' },
  { label: 'Córdoba', value: 'COR' },
  { label: 'Cundinamarca', value: 'CUN' },
  { label: 'Guainía', value: 'GUA' },
  { label: 'Guaviare', value: 'GUV' },
  { label: 'Huila', value: 'HUI' },
  { label: 'La Guajira', value: 'LAG' },
  { label: 'Magdalena', value: 'MAG' },
  { label: 'Meta', value: 'MET' },
  { label: 'Nariño', value: 'NAR' },
  { label: 'Norte de Santander', value: 'NSA' },
  { label: 'Putumayo', value: 'PUT' },
  { label: 'Quindío', value: 'QUI' },
  { label: 'Risaralda', value: 'RIS' },
  { label: 'San Andrés y Providencia', value: 'SAP' },
  { label: 'Santander', value: 'SAN' },
  { label: 'Sucre', value: 'SUC' },
  { label: 'Tolima', value: 'TOL' },
  { label: 'Valle del Cauca', value: 'VAC' },
  { label: 'Vaupés', value: 'VAU' },
  { label: 'Vichada', value: 'VID' },

  // Chile
  { label: 'Arica y Parinacota', value: 'AP' },
  { label: 'Tarapacá', value: 'TA' },
  { label: 'Antofagasta', value: 'AN' },
  { label: 'Atacama', value: 'AT' },
  { label: 'Coquimbo', value: 'CQ' },
  { label: 'Valparaíso', value: 'VS' },
  { label: 'Metropolitana de Santiago', value: 'RM' },
  { label: "O'Higgins", value: 'LI' },
  { label: 'Maule', value: 'ML' },
  { label: 'Ñuble', value: 'NB' },
  { label: 'Biobío', value: 'BI' },
  { label: 'La Araucanía', value: 'AR-CL' },
  { label: 'Los Ríos', value: 'LR-CL' },
  { label: 'Los Lagos', value: 'LL' },
  { label: 'Aysén', value: 'AI' },
  { label: 'Magallanes', value: 'MA' },

  // Opción para otros estados
  { label: 'Otro', value: 'OTHER' },
]
