import * as LucideIcons from 'lucide-react'

export const availableIcons = [
  // Navegación y UI Básico
  'Home',
  'Menu',
  'X',
  'Search',
  'Settings',
  'MoreHorizontal',
  'MoreVertical',
  'ChevronLeft',
  'ChevronRight',
  'ChevronUp',
  'ChevronDown',
  'ChevronsLeft',
  'ChevronsRight',
  'ChevronsUp',
  'ChevronsDown',
  'ArrowLeft',
  'ArrowRight',
  'ArrowUp',
  'ArrowDown',
  'ArrowUpRight',
  'ArrowDownRight',
  'ArrowUpLeft',
  'ArrowDownLeft',
  'Navigation',
  'Compass',
  'Move',
  'Maximize',
  'Maximize2',
  'Minimize',
  'Minimize2',
  'Expand',
  'Shrink',
  'ZoomIn',
  'ZoomOut',
  'Fullscreen',

  // Acciones y Edición
  'Plus',
  'Minus',
  'Edit',
  'Edit2',
  'Edit3',
  'Pencil',
  'PenTool',
  'Save',
  'Trash',
  'Trash2',
  'Delete',
  'Copy',
  'Clipboard',
  'ClipboardCopy',
  'ClipboardCheck',
  'ClipboardList',
  'Check',
  'CheckCircle',
  'CheckCircle2',
  'CheckSquare',
  'XCircle',
  'XSquare',
  'Undo',
  'Redo',
  'RotateCw',
  'RotateCcw',
  'RefreshCw',
  'RefreshCcw',
  'Download',
  'Upload',
  'Share',
  'Share2',
  'Forward',
  'Reply',
  'ReplyAll',

  // Usuarios y Perfiles
  'User',
  'Users',
  'UserPlus',
  'UserMinus',
  'UserCheck',
  'UserX',
  'UserCog',
  'Contact',
  'Smile',
  'Meh',
  'Frown',
  'Heart',
  'ThumbsUp',
  'ThumbsDown',

  // Comunicación
  'Mail',
  'MailOpen',
  'Send',
  'MessageSquare',
  'MessageCircle',
  'Phone',
  'PhoneCall',
  'PhoneIncoming',
  'PhoneOutgoing',
  'PhoneMissed',
  'PhoneForwarded',
  'PhoneOff',
  'Video',
  'VideoOff',
  'Voicemail',
  'AtSign',

  // Alertas y Notificaciones
  'Bell',
  'BellOff',
  'BellRing',
  'AlertCircle',
  'AlertTriangle',
  'AlertOctagon',
  'Info',
  'HelpCircle',
  'Ban',
  'ShieldAlert',
  'ShieldCheck',
  'Shield',
  'ShieldOff',

  // Archivos y Documentos
  'File',
  'FileText',
  'FilePlus',
  'FileMinus',
  'FileEdit',
  'Files',
  'Folder',
  'FolderPlus',
  'FolderMinus',
  'FolderOpen',
  'Folders',
  'FileArchive',
  'FileCode',
  'FileJson',
  'FileSpreadsheet',
  'FileImage',
  'FileVideo',
  'FileAudio',
  'FilePdf',

  // Multimedia
  'Image',
  'Images',
  'Camera',
  'CameraOff',
  'Music',
  'Play',
  'Pause',
  'Square',
  'Circle',
  'SkipBack',
  'SkipForward',
  'FastForward',
  'Rewind',
  'Volume',
  'Volume1',
  'Volume2',
  'VolumeX',
  'Mic',
  'MicOff',
  'Film',

  // Comercio y Finanzas
  'ShoppingCart',
  'ShoppingBag',
  'CreditCard',
  'Wallet',
  'DollarSign',
  'Euro',
  'Percent',
  'Tag',
  'Tags',
  'Receipt',
  'Banknote',
  'Package',
  'Package2',
  'PackageCheck',
  'PackageX',
  'PackagePlus',
  'PackageMinus',
  'Gift',
  'Award',
  'TrendingUp',
  'TrendingDown',
  'BarChart',
  'BarChart2',
  'BarChart3',
  'LineChart',
  'PieChart',
  'Activity',

  // Tiempo y Calendario
  'Calendar',
  'CalendarDays',
  'CalendarCheck',
  'CalendarX',
  'CalendarPlus',
  'CalendarMinus',
  'Clock',
  'Clock1',
  'Clock2',
  'Clock3',
  'Clock4',
  'Clock5',
  'Clock6',
  'Clock7',
  'Clock8',
  'Clock9',
  'Clock10',
  'Clock11',
  'Clock12',
  'Timer',
  'TimerOff',
  'Hourglass',
  'AlarmClock',

  // Ubicación y Mapas
  'MapPin',
  'Map',
  'Navigation2',
  'Globe',
  'Globe2',
  'Milestone',
  'Flag',
  'FlagTriangleRight',
  'Locate',
  'LocateFixed',
  'LocateOff',

  // Dispositivos y Tecnología
  'Laptop',
  'Monitor',
  'Smartphone',
  'Tablet',
  'Watch',
  'Tv',
  'Speaker',
  'Headphones',
  'Mouse',
  'Keyboard',
  'Printer',
  'HardDrive',
  'Server',
  'Database',
  'Cpu',
  'Battery',
  'BatteryCharging',
  'BatteryFull',
  'BatteryLow',
  'BatteryMedium',
  'BatteryWarning',
  'Wifi',
  'WifiOff',
  'Bluetooth',
  'BluetoothConnected',
  'BluetoothOff',
  'Cast',
  'Usb',
  'Power',
  'PowerOff',
  'Plug',
  'Zap',
  'ZapOff',

  // Desarrollo y Código
  'Code',
  'Code2',
  'Terminal',
  'Command',
  'GitBranch',
  'GitCommit',
  'GitMerge',
  'GitPullRequest',
  'Github',
  'Gitlab',
  'Bug',
  'Wrench',
  'Hammer',
  'Sliders',
  'SlidersHorizontal',
  'Construction',

  // Seguridad
  'Lock',
  'LockOpen',
  'Unlock',
  'Key',
  'KeyRound',
  'Eye',
  'EyeOff',
  'Fingerprint',
  'Scan',
  'ScanLine',

  // Organización y Layout
  'Grid',
  'Grid2x2',
  'Grid3x3',
  'List',
  'LayoutGrid',
  'LayoutList',
  'LayoutDashboard',
  'LayoutTemplate',
  'Columns',
  'Rows',
  'Table',
  'Table2',
  'PanelLeft',
  'PanelRight',
  'PanelTop',
  'PanelBottom',
  'Sidebar',
  'SidebarOpen',
  'SidebarClose',

  // Ordenamiento y Filtros
  'Filter',
  'FilterX',
  'SortAsc',
  'SortDesc',
  'ArrowUpDown',
  'ArrowDownUp',
  'MoveUp',
  'MoveDown',
  'MoveLeft',
  'MoveRight',

  // Marcadores y Favoritos
  'Star',
  'Bookmark',
  'BookmarkPlus',
  'BookmarkMinus',
  'BookOpen',
  'Book',
  'Library',

  // Conectividad y Enlaces
  'Link',
  'Link2',
  'ExternalLink',
  'Unlink',
  'Paperclip',
  'Anchor',

  // Clima
  'Sun',
  'Moon',
  'Cloud',
  'CloudRain',
  'CloudSnow',
  'CloudDrizzle',
  'CloudLightning',
  'CloudFog',
  'CloudOff',
  'Sunrise',
  'Sunset',
  'Thermometer',
  'ThermometerSun',
  'ThermometerSnowflake',
  'Snowflake',
  'Wind',
  'Droplet',
  'Droplets',
  'Umbrella',

  // Transporte
  'Car',
  'Truck',
  'Bus',
  'Bike',
  'Plane',
  'PlaneTakeoff',
  'PlaneLanding',
  'Ship',
  'Train',
  'Rocket',
  'Fuel',

  // Edificios y Lugares
  'Building',
  'Building2',
  'Factory',
  'Warehouse',
  'Store',
  'Home',
  'Hotel',
  'Church',
  'School',
  'Hospital',
  'TreePine',
  'Trees',
  'Tent',

  // Comida y Bebida
  'Coffee',
  'Beer',
  'Wine',
  'Pizza',
  'Cake',
  'Apple',
  'Salad',
  'Utensils',
  'UtensilsCrossed',
  'CupSoda',
  'IceCream',

  // Formas y Símbolos
  'Circle',
  'Square',
  'Triangle',
  'Pentagon',
  'Hexagon',
  'Octagon',
  'Diamond',
  'Hash',
  'Asterisk',
  'Minus',
  'Plus',
  'Equal',
  'Infinity',

  // Herramientas
  'Briefcase',
  'Tool',
  'Paintbrush',
  'Pipette',
  'Eraser',
  'Scissors',
  'Ruler',
  'Magnet',
  'Drill',
  'Saw',

  // Salud y Médico
  'HeartPulse',
  'Stethoscope',
  'Syringe',
  'Pill',
  'Bandage',
  'Activity',
  'Cross',

  // Accesibilidad
  'Accessibility',
  'EarOff',
  'Ear',
  'Focus',
  'Glasses',
  'Contrast',

  // Otros
  'Flame',
  'Sparkles',
  'Lightbulb',
  'Crown',
  'Medal',
  'Trophy',
  'Target',
  'Radio',
  'Rss',
  'QrCode',
  'Barcode',
  'ScanBarcode',
  'CircleDot',
  'Gauge',
] as const

export type IconName = (typeof availableIcons)[number]

// Mapeo de iconos a sus labels en español
export const iconLabelsES: Record<IconName, string> = {
  // Navegación y UI Básico
  Home: 'Inicio',
  Menu: 'Menú',
  X: 'Cerrar',
  Search: 'Buscar',
  Settings: 'Configuración',
  MoreHorizontal: 'Más Horizontal',
  MoreVertical: 'Más Vertical',
  ChevronLeft: 'Flecha Izquierda',
  ChevronRight: 'Flecha Derecha',
  ChevronUp: 'Flecha Arriba',
  ChevronDown: 'Flecha Abajo',
  ChevronsLeft: 'Flechas Izquierda',
  ChevronsRight: 'Flechas Derecha',
  ChevronsUp: 'Flechas Arriba',
  ChevronsDown: 'Flechas Abajo',
  ArrowLeft: 'Flecha Izquierda',
  ArrowRight: 'Flecha Derecha',
  ArrowUp: 'Flecha Arriba',
  ArrowDown: 'Flecha Abajo',
  ArrowUpRight: 'Flecha Arriba Derecha',
  ArrowDownRight: 'Flecha Abajo Derecha',
  ArrowUpLeft: 'Flecha Arriba Izquierda',
  ArrowDownLeft: 'Flecha Abajo Izquierda',
  Navigation: 'Navegación',
  Compass: 'Brújula',
  Move: 'Mover',
  Maximize: 'Maximizar',
  Maximize2: 'Maximizar 2',
  Minimize: 'Minimizar',
  Minimize2: 'Minimizar 2',
  Expand: 'Expandir',
  Shrink: 'Contraer',
  ZoomIn: 'Acercar',
  ZoomOut: 'Alejar',
  Fullscreen: 'Pantalla Completa',

  // Acciones y Edición
  Plus: 'Más',
  Minus: 'Menos',
  Edit: 'Editar',
  Edit2: 'Editar 2',
  Edit3: 'Editar 3',
  Pencil: 'Lápiz',
  PenTool: 'Pluma',
  Save: 'Guardar',
  Trash: 'Eliminar',
  Trash2: 'Papelera',
  Delete: 'Borrar',
  Copy: 'Copiar',
  Clipboard: 'Portapapeles',
  ClipboardCopy: 'Copiar al Portapapeles',
  ClipboardCheck: 'Portapapeles Verificado',
  ClipboardList: 'Lista Portapapeles',
  Check: 'Verificar',
  CheckCircle: 'Verificado',
  CheckCircle2: 'Verificado 2',
  CheckSquare: 'Casilla Marcada',
  XCircle: 'Cerrar Círculo',
  XSquare: 'Cerrar Cuadrado',
  Undo: 'Deshacer',
  Redo: 'Rehacer',
  RotateCw: 'Rotar Derecha',
  RotateCcw: 'Rotar Izquierda',
  RefreshCw: 'Actualizar',
  RefreshCcw: 'Actualizar Inverso',
  Download: 'Descargar',
  Upload: 'Subir',
  Share: 'Compartir',
  Share2: 'Compartir 2',
  Forward: 'Reenviar',
  Reply: 'Responder',
  ReplyAll: 'Responder a Todos',

  // Usuarios y Perfiles
  User: 'Usuario',
  Users: 'Usuarios',
  UserPlus: 'Agregar Usuario',
  UserMinus: 'Quitar Usuario',
  UserCheck: 'Usuario Verificado',
  UserX: 'Usuario Rechazado',
  UserCog: 'Configurar Usuario',
  Contact: 'Contacto',
  Smile: 'Sonrisa',
  Meh: 'Indiferente',
  Frown: 'Triste',
  Heart: 'Corazón',
  ThumbsUp: 'Me Gusta',
  ThumbsDown: 'No Me Gusta',

  // Comunicación
  Mail: 'Correo',
  MailOpen: 'Correo Abierto',
  Send: 'Enviar',
  MessageSquare: 'Mensaje',
  MessageCircle: 'Chat',
  Phone: 'Teléfono',
  PhoneCall: 'Llamada',
  PhoneIncoming: 'Llamada Entrante',
  PhoneOutgoing: 'Llamada Saliente',
  PhoneMissed: 'Llamada Perdida',
  PhoneForwarded: 'Llamada Reenviada',
  PhoneOff: 'Teléfono Apagado',
  Video: 'Video',
  VideoOff: 'Video Desactivado',
  Voicemail: 'Buzón de Voz',
  AtSign: 'Arroba',

  // Alertas y Notificaciones
  Bell: 'Notificación',
  BellOff: 'Notificaciones Desactivadas',
  BellRing: 'Campana Sonando',
  AlertCircle: 'Alerta Circular',
  AlertTriangle: 'Alerta',
  AlertOctagon: 'Alerta Octágono',
  Info: 'Información',
  HelpCircle: 'Ayuda',
  Ban: 'Prohibido',
  ShieldAlert: 'Escudo Alerta',
  ShieldCheck: 'Escudo Verificado',
  Shield: 'Escudo',
  ShieldOff: 'Escudo Desactivado',

  // Archivos y Documentos
  File: 'Archivo',
  FileText: 'Documento',
  FilePlus: 'Agregar Archivo',
  FileMinus: 'Quitar Archivo',
  FileEdit: 'Editar Archivo',
  Files: 'Archivos',
  Folder: 'Carpeta',
  FolderPlus: 'Agregar Carpeta',
  FolderMinus: 'Quitar Carpeta',
  FolderOpen: 'Carpeta Abierta',
  Folders: 'Carpetas',
  FileArchive: 'Archivo Comprimido',
  FileCode: 'Código',
  FileJson: 'Archivo JSON',
  FileSpreadsheet: 'Hoja de Cálculo',
  FileImage: 'Imagen',
  FileVideo: 'Video',
  FileAudio: 'Audio',
  FilePdf: 'PDF',

  // Multimedia
  Image: 'Imagen',
  Images: 'Imágenes',
  Camera: 'Cámara',
  CameraOff: 'Cámara Desactivada',
  Music: 'Música',
  Play: 'Reproducir',
  Pause: 'Pausar',
  Square: 'Cuadrado',
  Circle: 'Círculo',
  SkipBack: 'Retroceder',
  SkipForward: 'Avanzar',
  FastForward: 'Avance Rápido',
  Rewind: 'Rebobinar',
  Volume: 'Volumen',
  Volume1: 'Volumen Bajo',
  Volume2: 'Volumen Alto',
  VolumeX: 'Sin Volumen',
  Mic: 'Micrófono',
  MicOff: 'Micrófono Desactivado',
  Film: 'Película',

  // Comercio y Finanzas
  ShoppingCart: 'Carrito',
  ShoppingBag: 'Bolsa de Compras',
  CreditCard: 'Tarjeta de Crédito',
  Wallet: 'Cartera',
  DollarSign: 'Dólar',
  Euro: 'Euro',
  Percent: 'Porcentaje',
  Tag: 'Etiqueta',
  Tags: 'Etiquetas',
  Receipt: 'Recibo',
  Banknote: 'Billete',
  Package: 'Paquete',
  Package2: 'Paquete 2',
  PackageCheck: 'Paquete Verificado',
  PackageX: 'Paquete Rechazado',
  PackagePlus: 'Agregar Paquete',
  PackageMinus: 'Quitar Paquete',
  Gift: 'Regalo',
  Award: 'Premio',
  TrendingUp: 'Tendencia Alcista',
  TrendingDown: 'Tendencia Bajista',
  BarChart: 'Gráfico de Barras',
  BarChart2: 'Gráfico de Barras 2',
  BarChart3: 'Gráfico de Barras 3',
  LineChart: 'Gráfico de Líneas',
  PieChart: 'Gráfico Circular',
  Activity: 'Actividad',

  // Tiempo y Calendario
  Calendar: 'Calendario',
  CalendarDays: 'Días del Calendario',
  CalendarCheck: 'Calendario Verificado',
  CalendarX: 'Calendario Cancelado',
  CalendarPlus: 'Agregar al Calendario',
  CalendarMinus: 'Quitar del Calendario',
  Clock: 'Reloj',
  Clock1: 'Reloj 1',
  Clock2: 'Reloj 2',
  Clock3: 'Reloj 3',
  Clock4: 'Reloj 4',
  Clock5: 'Reloj 5',
  Clock6: 'Reloj 6',
  Clock7: 'Reloj 7',
  Clock8: 'Reloj 8',
  Clock9: 'Reloj 9',
  Clock10: 'Reloj 10',
  Clock11: 'Reloj 11',
  Clock12: 'Reloj 12',
  Timer: 'Temporizador',
  TimerOff: 'Temporizador Desactivado',
  Hourglass: 'Reloj de Arena',
  AlarmClock: 'Despertador',

  // Ubicación y Mapas
  MapPin: 'Ubicación',
  Map: 'Mapa',
  Navigation2: 'Navegación 2',
  Globe: 'Globo',
  Globe2: 'Globo 2',
  Milestone: 'Hito',
  Flag: 'Bandera',
  FlagTriangleRight: 'Bandera Triangular',
  Locate: 'Localizar',
  LocateFixed: 'Ubicación Fija',
  LocateOff: 'Localización Desactivada',

  // Dispositivos y Tecnología
  Laptop: 'Portátil',
  Monitor: 'Monitor',
  Smartphone: 'Teléfono Inteligente',
  Tablet: 'Tableta',
  Watch: 'Reloj',
  Tv: 'Televisión',
  Speaker: 'Altavoz',
  Headphones: 'Auriculares',
  Mouse: 'Ratón',
  Keyboard: 'Teclado',
  Printer: 'Impresora',
  HardDrive: 'Disco Duro',
  Server: 'Servidor',
  Database: 'Base de Datos',
  Cpu: 'Procesador',
  Battery: 'Batería',
  BatteryCharging: 'Batería Cargando',
  BatteryFull: 'Batería Llena',
  BatteryLow: 'Batería Baja',
  BatteryMedium: 'Batería Media',
  BatteryWarning: 'Batería Advertencia',
  Wifi: 'WiFi',
  WifiOff: 'WiFi Desactivado',
  Bluetooth: 'Bluetooth',
  BluetoothConnected: 'Bluetooth Conectado',
  BluetoothOff: 'Bluetooth Desactivado',
  Cast: 'Transmitir',
  Usb: 'USB',
  Power: 'Encender',
  PowerOff: 'Apagar',
  Plug: 'Enchufe',
  Zap: 'Rayo',
  ZapOff: 'Rayo Desactivado',

  // Desarrollo y Código
  Code: 'Código',
  Code2: 'Código 2',
  Terminal: 'Terminal',
  Command: 'Comando',
  GitBranch: 'Rama Git',
  GitCommit: 'Commit Git',
  GitMerge: 'Fusionar Git',
  GitPullRequest: 'Pull Request',
  Github: 'GitHub',
  Gitlab: 'GitLab',
  Bug: 'Error',
  Wrench: 'Llave Inglesa',
  Hammer: 'Martillo',
  Sliders: 'Controles',
  SlidersHorizontal: 'Controles Horizontales',
  Construction: 'Construcción',

  // Seguridad
  Lock: 'Bloqueado',
  LockOpen: 'Abierto',
  Unlock: 'Desbloqueado',
  Key: 'Llave',
  KeyRound: 'Llave Redonda',
  Eye: 'Ver',
  EyeOff: 'Ocultar',
  Fingerprint: 'Huella Digital',
  Scan: 'Escanear',
  ScanLine: 'Línea de Escaneo',

  // Organización y Layout
  Grid: 'Cuadrícula',
  Grid2x2: 'Cuadrícula 2x2',
  Grid3x3: 'Cuadrícula 3x3',
  List: 'Lista',
  LayoutGrid: 'Diseño Cuadrícula',
  LayoutList: 'Diseño Lista',
  LayoutDashboard: 'Panel de Control',
  LayoutTemplate: 'Plantilla',
  Columns: 'Columnas',
  Rows: 'Filas',
  Table: 'Tabla',
  Table2: 'Tabla 2',
  PanelLeft: 'Panel Izquierdo',
  PanelRight: 'Panel Derecho',
  PanelTop: 'Panel Superior',
  PanelBottom: 'Panel Inferior',
  Sidebar: 'Barra Lateral',
  SidebarOpen: 'Barra Lateral Abierta',
  SidebarClose: 'Barra Lateral Cerrada',

  // Ordenamiento y Filtros
  Filter: 'Filtro',
  FilterX: 'Quitar Filtro',
  SortAsc: 'Ordenar Ascendente',
  SortDesc: 'Ordenar Descendente',
  ArrowUpDown: 'Ordenar',
  ArrowDownUp: 'Ordenar Inverso',
  MoveUp: 'Mover Arriba',
  MoveDown: 'Mover Abajo',
  MoveLeft: 'Mover Izquierda',
  MoveRight: 'Mover Derecha',

  // Marcadores y Favoritos
  Star: 'Estrella',
  Bookmark: 'Marcador',
  BookmarkPlus: 'Agregar Marcador',
  BookmarkMinus: 'Quitar Marcador',
  BookOpen: 'Libro Abierto',
  Book: 'Libro',
  Library: 'Biblioteca',

  // Conectividad y Enlaces
  Link: 'Enlace',
  Link2: 'Enlace 2',
  ExternalLink: 'Enlace Externo',
  Unlink: 'Desvincular',
  Paperclip: 'Clip',
  Anchor: 'Ancla',

  // Clima
  Sun: 'Sol',
  Moon: 'Luna',
  Cloud: 'Nube',
  CloudRain: 'Lluvia',
  CloudSnow: 'Nieve',
  CloudDrizzle: 'Llovizna',
  CloudLightning: 'Tormenta',
  CloudFog: 'Niebla',
  CloudOff: 'Sin Nubes',
  Sunrise: 'Amanecer',
  Sunset: 'Atardecer',
  Thermometer: 'Termómetro',
  ThermometerSun: 'Termómetro Sol',
  ThermometerSnowflake: 'Termómetro Frío',
  Snowflake: 'Copo de Nieve',
  Wind: 'Viento',
  Droplet: 'Gota',
  Droplets: 'Gotas',
  Umbrella: 'Paraguas',

  // Transporte
  Car: 'Automóvil',
  Truck: 'Camión',
  Bus: 'Autobús',
  Bike: 'Bicicleta',
  Plane: 'Avión',
  PlaneTakeoff: 'Despegue',
  PlaneLanding: 'Aterrizaje',
  Ship: 'Barco',
  Train: 'Tren',
  Rocket: 'Cohete',
  Fuel: 'Combustible',

  // Edificios y Lugares
  Building: 'Edificio',
  Building2: 'Edificio 2',
  Factory: 'Fábrica',
  Warehouse: 'Almacén',
  Store: 'Tienda',
  Hotel: 'Hotel',
  Church: 'Iglesia',
  School: 'Escuela',
  Hospital: 'Hospital',
  TreePine: 'Pino',
  Trees: 'Árboles',
  Tent: 'Tienda de Campaña',

  // Comida y Bebida
  Coffee: 'Café',
  Beer: 'Cerveza',
  Wine: 'Vino',
  Pizza: 'Pizza',
  Cake: 'Pastel',
  Apple: 'Manzana',
  Salad: 'Ensalada',
  Utensils: 'Cubiertos',
  UtensilsCrossed: 'Cubiertos Cruzados',
  CupSoda: 'Refresco',
  IceCream: 'Helado',

  // Formas y Símbolos
  Triangle: 'Triángulo',
  Pentagon: 'Pentágono',
  Hexagon: 'Hexágono',
  Octagon: 'Octágono',
  Diamond: 'Diamante',
  Hash: 'Numeral',
  Asterisk: 'Asterisco',
  Equal: 'Igual',
  Infinity: 'Infinito',

  // Herramientas
  Briefcase: 'Maletín',
  Tool: 'Herramienta',
  Paintbrush: 'Pincel',
  Pipette: 'Cuentagotas',
  Eraser: 'Borrador',
  Scissors: 'Tijeras',
  Ruler: 'Regla',
  Magnet: 'Imán',
  Drill: 'Taladro',
  Saw: 'Sierra',

  // Salud y Médico
  HeartPulse: 'Pulso',
  Stethoscope: 'Estetoscopio',
  Syringe: 'Jeringa',
  Pill: 'Pastilla',
  Bandage: 'Vendaje',
  Cross: 'Cruz',

  // Accesibilidad
  Accessibility: 'Accesibilidad',
  EarOff: 'Oído Desactivado',
  Ear: 'Oído',
  Focus: 'Enfoque',
  Glasses: 'Gafas',
  Contrast: 'Contraste',

  // Otros
  Flame: 'Fuego',
  Sparkles: 'Destellos',
  Lightbulb: 'Bombilla',
  Crown: 'Corona',
  Medal: 'Medalla',
  Trophy: 'Trofeo',
  Target: 'Objetivo',
  Radio: 'Radio',
  Rss: 'RSS',
  QrCode: 'Código QR',
  Barcode: 'Código de Barras',
  ScanBarcode: 'Escanear Código',
  CircleDot: 'Punto Circular',
  Gauge: 'Indicador',
}

// Función para obtener el componente de icono por nombre
export const getIconComponent = (iconName: string) => {
  return (LucideIcons as any)[iconName] || null
}

// Función para verificar si un icono existe
export const isValidIcon = (iconName: string): boolean => {
  return availableIcons.includes(iconName as IconName)
}

// Función para obtener el label en español de un icono
export const getIconLabel = (iconName: string): string => {
  return iconLabelsES[iconName as IconName] || iconName
}

// Función para buscar iconos por label en español o nombre en inglés
export const searchIcons = (searchTerm: string): IconName[] => {
  if (!searchTerm) return [...availableIcons]

  const term = searchTerm.toLowerCase()
  return availableIcons.filter((iconName) => {
    const label = iconLabelsES[iconName].toLowerCase()
    const name = iconName.toLowerCase()
    return label.includes(term) || name.includes(term)
  })
}
