import * as LucideIcons from 'lucide-react'

export const availableIcons = [
  // Navegación y UI Básico
  'Home',
  'Menu',
  'X',
  'Search',
  'Settings',
  'MoreHorizontal',
  'MoreVertical',
  'ChevronLeft',
  'ChevronRight',
  'ChevronUp',
  'ChevronDown',
  'ChevronsLeft',
  'ChevronsRight',
  'ChevronsUp',
  'ChevronsDown',
  'ArrowLeft',
  'ArrowRight',
  'ArrowUp',
  'ArrowDown',
  'ArrowUpRight',
  'ArrowDownRight',
  'ArrowUpLeft',
  'ArrowDownLeft',
  'Navigation',
  'Compass',
  'Move',
  'Maximize',
  'Maximize2',
  'Minimize',
  'Minimize2',
  'Expand',
  'Shrink',
  'ZoomIn',
  'ZoomOut',
  'Fullscreen',
  'SidebarOpen',
  'SidebarClose',
  'PanelLeft',
  'PanelRight',
  'PanelTop',
  'PanelBottom',

  // Acciones y Edición
  'Plus',
  'Minus',
  'Edit',
  'Edit2',
  'Edit3',
  'Pencil',
  'PenTool',
  'Save',
  'Trash',
  'Trash2',
  'Delete',
  'Copy',
  'Clipboard',
  'ClipboardCopy',
  'ClipboardCheck',
  'ClipboardList',
  'Check',
  'CheckCircle',
  'CheckCircle2',
  'CheckSquare',
  'XCircle',
  'XSquare',
  'Undo',
  'Redo',
  'RotateCw',
  'RotateCcw',
  'RefreshCw',
  'RefreshCcw',
  'Download',
  'Upload',
  'Share',
  'Share2',
  'Forward',
  'Reply',
  'ReplyAll',
  'Import',
  'Export',

  // Usuarios y Perfiles
  'User',
  'Users',
  'UserPlus',
  'UserMinus',
  'UserCheck',
  'UserX',
  'UserCog',
  'Contact',
  'Smile',
  'Meh',
  'Frown',
  'Heart',
  'ThumbsUp',
  'ThumbsDown',
  'Users2',
  'UserCircle',
  'UserSquare',

  // Comunicación
  'Mail',
  'MailOpen',
  'Send',
  'MessageSquare',
  'MessageCircle',
  'Phone',
  'PhoneCall',
  'PhoneIncoming',
  'PhoneOutgoing',
  'PhoneMissed',
  'PhoneForwarded',
  'PhoneOff',
  'Video',
  'VideoOff',
  'Voicemail',
  'AtSign',
  'Inbox',
  'Mails',

  // Alertas y Notificaciones
  'Bell',
  'BellOff',
  'BellRing',
  'AlertCircle',
  'AlertTriangle',
  'AlertOctagon',
  'Info',
  'HelpCircle',
  'Ban',
  'ShieldAlert',
  'ShieldCheck',
  'Shield',
  'ShieldOff',
  'Siren',

  // Archivos y Documentos
  'File',
  'FileText',
  'FilePlus',
  'FileMinus',
  'FileEdit',
  'Files',
  'Folder',
  'FolderPlus',
  'FolderMinus',
  'FolderOpen',
  'Folders',
  'FileArchive',
  'FileCode',
  'FileJson',
  'FileSpreadsheet',
  'FileImage',
  'FileVideo',
  'FileAudio',
  'FilePdf',
  'FileType',
  'FileX',
  'FileCheck',
  'FolderX',
  'FolderCheck',

  // Multimedia
  'Image',
  'Images',
  'Camera',
  'CameraOff',
  'Music',
  'Play',
  'Pause',
  'Square',
  'Circle',
  'SkipBack',
  'SkipForward',
  'FastForward',
  'Rewind',
  'Volume',
  'Volume1',
  'Volume2',
  'VolumeX',
  'Mic',
  'MicOff',
  'Film',
  'PlayCircle',
  'PauseCircle',
  'StopCircle',

  // Comercio y Finanzas
  'ShoppingCart',
  'ShoppingBag',
  'CreditCard',
  'Wallet',
  'DollarSign',
  'Euro',
  'Percent',
  'Tag',
  'Tags',
  'Receipt',
  'Banknote',
  'Package',
  'Package2',
  'PackageCheck',
  'PackageX',
  'PackagePlus',
  'PackageMinus',
  'Gift',
  'Award',
  'TrendingUp',
  'TrendingDown',
  'BarChart',
  'BarChart2',
  'BarChart3',
  'LineChart',
  'PieChart',
  'Activity',
  'Calculator',
  'Coins',

  // Tiempo y Calendario
  'Calendar',
  'CalendarDays',
  'CalendarCheck',
  'CalendarX',
  'CalendarPlus',
  'CalendarMinus',
  'Clock',
  'Clock1',
  'Clock2',
  'Clock3',
  'Clock4',
  'Clock5',
  'Clock6',
  'Clock7',
  'Clock8',
  'Clock9',
  'Clock10',
  'Clock11',
  'Clock12',
  'Timer',
  'TimerOff',
  'Hourglass',
  'AlarmClock',
  'CalendarRange',

  // Ubicación y Mapas
  'MapPin',
  'Map',
  'Navigation2',
  'Globe',
  'Globe2',
  'Milestone',
  'Flag',
  'FlagTriangleRight',
  'Locate',
  'LocateFixed',
  'LocateOff',
  'Route',
  'Signpost',

  // Dispositivos y Tecnología
  'Laptop',
  'Monitor',
  'Smartphone',
  'Tablet',
  'Watch',
  'Tv',
  'Speaker',
  'Headphones',
  'Mouse',
  'Keyboard',
  'Printer',
  'HardDrive',
  'Server',
  'Database',
  'Cpu',
  'Battery',
  'BatteryCharging',
  'BatteryFull',
  'BatteryLow',
  'BatteryMedium',
  'BatteryWarning',
  'Wifi',
  'WifiOff',
  'Bluetooth',
  'BluetoothConnected',
  'BluetoothOff',
  'Cast',
  'Usb',
  'Power',
  'PowerOff',
  'Plug',
  'Zap',
  'ZapOff',
  'MonitorSpeaker',
  'Gamepad',
  'Gamepad2',

  // Desarrollo y Código
  'Code',
  'Code2',
  'Terminal',
  'Command',
  'GitBranch',
  'GitCommit',
  'GitMerge',
  'GitPullRequest',
  'Github',
  'Gitlab',
  'Bug',
  'Wrench',
  'Hammer',
  'Sliders',
  'SlidersHorizontal',
  'Construction',
  'Binary',
  'Braces',
  'Brackets',

  // Seguridad
  'Lock',
  'LockOpen',
  'Unlock',
  'Key',
  'KeyRound',
  'Eye',
  'EyeOff',
  'Fingerprint',
  'Scan',
  'ScanLine',
  'ShieldX',
  'KeySquare',

  // Organización y Layout
  'Grid',
  'Grid2x2',
  'Grid3x3',
  'List',
  'LayoutGrid',
  'LayoutList',
  'LayoutDashboard',
  'LayoutTemplate',
  'Columns',
  'Rows',
  'Table',
  'Table2',
  'Sidebar',
  'AlignLeft',
  'AlignCenter',
  'AlignRight',
  'AlignJustify',

  // Ordenamiento y Filtros
  'Filter',
  'FilterX',
  'SortAsc',
  'SortDesc',
  'ArrowUpDown',
  'ArrowDownUp',
  'MoveUp',
  'MoveDown',
  'MoveLeft',
  'MoveRight',
  'Move3d',
  'Shuffle',

  // Marcadores y Favoritos
  'Star',
  'Bookmark',
  'BookmarkPlus',
  'BookmarkMinus',
  'BookOpen',
  'Book',
  'Library',
  'StarHalf',
  'StarOff',

  // Conectividad y Enlaces
  'Link',
  'Link2',
  'ExternalLink',
  'Unlink',
  'Paperclip',
  'Anchor',
  'Chain',
  'Unplug',

  // Clima
  'Sun',
  'Moon',
  'Cloud',
  'CloudRain',
  'CloudSnow',
  'CloudDrizzle',
  'CloudLightning',
  'CloudFog',
  'CloudOff',
  'Sunrise',
  'Sunset',
  'Thermometer',
  'ThermometerSun',
  'ThermometerSnowflake',
  'Snowflake',
  'Wind',
  'Droplet',
  'Droplets',
  'Umbrella',
  'Rainbow',
  'Tornado',

  // Transporte
  'Car',
  'Truck',
  'Bus',
  'Bike',
  'Plane',
  'PlaneTakeoff',
  'PlaneLanding',
  'Ship',
  'Train',
  'Rocket',
  'Fuel',
  'CarFront',
  'Ambulance',
  'Taxi',

  // Edificios y Lugares
  'Building',
  'Building2',
  'Factory',
  'Warehouse',
  'Store',
  'Hotel',
  'Church',
  'School',
  'Hospital',
  'TreePine',
  'Trees',
  'Tent',
  'Castle',
  'Landmark',

  // Comida y Bebida
  'Coffee',
  'Beer',
  'Wine',
  'Pizza',
  'Cake',
  'Apple',
  'Salad',
  'Utensils',
  'UtensilsCrossed',
  'CupSoda',
  'IceCream',
  'Cherry',
  'Grape',
  'Sandwich',

  // Formas y Símbolos
  'Triangle',
  'Pentagon',
  'Hexagon',
  'Octagon',
  'Diamond',
  'Hash',
  'Asterisk',
  'Equal',
  'Infinity',
  'Shapes',

  // Herramientas
  'Briefcase',
  'Tool',
  'Paintbrush',
  'Pipette',
  'Eraser',
  'Scissors',
  'Ruler',
  'Magnet',
  'Drill',
  'Saw',
  'Screwdriver',
  'Spanner',

  // Salud y Médico
  'HeartPulse',
  'Stethoscope',
  'Syringe',
  'Pill',
  'Bandage',
  'Cross',
  'Dna',

  // Accesibilidad
  'Accessibility',
  'EarOff',
  'Ear',
  'Focus',
  'Glasses',
  'Contrast',

  // Deportes y Actividades
  'Dumbbell',
  'Football',
  'Trophy',
  'Medal',
  'Target',
  'Flame',

  // Naturaleza
  'Leaf',
  'Flower',
  'Flower2',
  'Bug',
  'Fish',
  'Bird',
  'Rabbit',
  'Squirrel',

  // Texto y Tipografía
  'Type',
  'Bold',
  'Italic',
  'Underline',
  'Strikethrough',
  'Subscript',
  'Superscript',
  'Quote',
  'Text',
  'TextCursor',
  'TextSelect',
  'Heading',
  'Heading1',
  'Heading2',
  'Heading3',
  'Heading4',
  'Heading5',
  'Heading6',
  'Paragraph',
  'CaseSensitive',
  'CaseUpper',
  'CaseLower',
  'RemoveFormatting',
  'WrapText',
  'IndentIncrease',
  'IndentDecrease',
  'ListOrdered',
  'ListUnordered',
  'ListChecks',
  'ListX',
  'ListPlus',
  'ListMinus',
  'ListStart',
  'ListEnd',
  'ListRestart',
  'ListTree',
  'ListVideo',
  'ListMusic',
  'ListFilter',

  // Matemáticas y Números
  'Minus',
  'X',
  'Divide',
  'Equal',
  'NotEqual',
  'GreaterThan',
  'LessThan',
  'GreaterThanEqual',
  'LessThanEqual',
  'PlusCircle',
  'MinusCircle',
  'XCircle',
  'DivideCircle',
  'EqualNot',
  'Sigma',
  'Pi',
  'Radical',
  'Infinity',
  'Function',
  'Variable',
  'Subscript',
  'Superscript',

  // Redes Sociales y Comunicación
  'Facebook',
  'Twitter',
  'Instagram',
  'Linkedin',
  'Youtube',
  'Twitch',
  'Discord',
  'Slack',
  'MessageSquare',
  'MessageCircle',
  'MessagesSquare',
  'Speech',
  'Quote',
  'AtSign',
  'Hash',
  'Mention',
  'Reply',
  'ReplyAll',
  'Forward',
  'Share',
  'Share2',
  'Send',
  'SendHorizontal',
  'Megaphone',
  'Volume',
  'VolumeOff',
  'Podcast',

  // Juegos y Entretenimiento
  'Gamepad',
  'Gamepad2',
  'Joystick',
  'Dice1',
  'Dice2',
  'Dice3',
  'Dice4',
  'Dice5',
  'Dice6',
  'Spade',
  'Club',
  'Heart',
  'Diamond',
  'Puzzle',
  'Target',
  'Crosshair',
  'Zap',
  'Flame',
  'Crown',
  'Trophy',
  'Medal',
  'Award',
  'Ribbon',
  'PartyPopper',
  'Sparkles',
  'Sparkle',
  'Stars',
  'Wand',
  'Wand2',
  'Magic',

  // Ciencia y Educación
  'GraduationCap',
  'BookOpen',
  'Book',
  'BookMarked',
  'Bookmark',
  'BookmarkPlus',
  'BookmarkMinus',
  'BookmarkCheck',
  'BookmarkX',
  'Library',
  'School',
  'University',
  'Microscope',
  'TestTube',
  'TestTubes',
  'FlaskConical',
  'FlaskRound',
  'Beaker',
  'Atom',
  'Dna',
  'Molecule',
  'Orbit',
  'Telescope',
  'Globe',
  'Globe2',
  'Earth',
  'Moon',
  'Sun',
  'Star',
  'Stars',
  'Comet',
  'Rocket',
  'Satellite',
  'SatelliteDish',

  // Herramientas de Diseño
  'Paintbrush2',
  'PaintBucket',
  'Eyedropper',
  'ColorWheel',
  'Brightness',
  'BrightnessUp',
  'BrightnessDown',
  'Layers',
  'Layers2',
  'Layers3',
  'Group',
  'Ungroup',
  'Combine',
  'Intersect',
  'Union',
  'Exclude',
  'Subtract',
  'Crop',
  'Scissors',
  'Move',
  'Move3d',
  'RotateCw',
  'RotateCcw',
  'FlipHorizontal',
  'FlipVertical',
  'Scale',
  'Resize',
  'Aspect',

  // Medios y Streaming
  'Radio',
  'Podcast',
  'Headphones',
  'Speaker',
  'Mic',
  'MicOff',
  'MicVocal',
  'AudioLines',
  'AudioWaveform',
  'Music',
  'Music2',
  'Music3',
  'Music4',
  'Disc',
  'Disc2',
  'Disc3',
  'DiscAlbum',
  'Cassette',
  'Vinyl',
  'Antenna',
  'Signal',
  'SignalHigh',
  'SignalLow',
  'SignalMedium',
  'SignalZero',
  'Wifi',
  'WifiOff',
  'WifiHigh',
  'WifiLow',
  'Cast',
  'Airplay',
  'Chromecast',
  'Tv',
  'Tv2',
  'MonitorPlay',
  'Projector',
  'Presentation',

  // Navegación Web
  'History',
  'SearchCheck',
  'SearchCode',
  'SearchSlash',
  'SearchX',

  // Estados y Indicadores
  'QuestionMark',
  'Loader',
  'Loader2',
  'LoaderCircle',
  'Spinner',
  'Ellipsis',
  'EllipsisVertical',
  'Dot',
  'CircleEllipsis',
  'SquareDot',
  'HeartOff',
  'HeartHandshake',
  'HeartCrack',
  'Laugh',
  'Angry',
  'Surprised',

  // Otros
  'Sparkles',
  'Lightbulb',
  'Crown',
  'Rss',
  'QrCode',
  'Barcode',
  'ScanBarcode',
  'CircleDot',
  'Gauge',
  'Palette',
  'Brush',
  'Wand',
  'Wand2',
  'Dice1',
  'Dice2',
  'Dice3',
  'Dice4',
  'Dice5',
  'Dice6',
  'Gem',
  'Diamond',
  'Coins',
  'Banknote',
  'CreditCard',
  'Wallet',
  'PiggyBank',
  'Vault',
  'Safe',
  'Key',
  'KeyRound',
  'KeySquare',
  'Lock',
  'LockOpen',
  'Unlock',
  'ShieldCheck',
  'Shield',
  'ShieldAlert',
  'ShieldX',
  'ShieldOff',
  'Verified',
  'BadgeCheck',
  'Badge',
  'BadgeAlert',
  'BadgeX',
  'BadgeHelp',
  'BadgeInfo',
  'BadgePlus',
  'BadgeMinus',
  'BadgeDollarSign',
  'BadgePercent',
] as const

export type IconName = (typeof availableIcons)[number]
// Mapeo de iconos a sus labels en español
export const iconLabelsES: Record<IconName, string> = {
  // Navegación y UI Básico
  Home: 'Inicio',
  Menu: 'Menú',
  X: 'Cerrar',
  Search: 'Buscar',
  Settings: 'Configuración',
  MoreHorizontal: 'Más Horizontal',
  MoreVertical: 'Más Vertical',
  ChevronLeft: 'Flecha Izquierda',
  ChevronRight: 'Flecha Derecha',
  ChevronUp: 'Flecha Arriba',
  ChevronDown: 'Flecha Abajo',
  ChevronsLeft: 'Flechas Izquierda',
  ChevronsRight: 'Flechas Derecha',
  ChevronsUp: 'Flechas Arriba',
  ChevronsDown: 'Flechas Abajo',
  ArrowLeft: 'Flecha Izquierda',
  ArrowRight: 'Flecha Derecha',
  ArrowUp: 'Flecha Arriba',
  ArrowDown: 'Flecha Abajo',
  ArrowUpRight: 'Flecha Arriba Derecha',
  ArrowDownRight: 'Flecha Abajo Derecha',
  ArrowUpLeft: 'Flecha Arriba Izquierda',
  ArrowDownLeft: 'Flecha Abajo Izquierda',
  Navigation: 'Navegación',
  Compass: 'Brújula',
  Move: 'Mover',
  Maximize: 'Maximizar',
  Maximize2: 'Maximizar 2',
  Minimize: 'Minimizar',
  Minimize2: 'Minimizar 2',
  Expand: 'Expandir',
  Shrink: 'Contraer',
  ZoomIn: 'Acercar',
  ZoomOut: 'Alejar',
  Fullscreen: 'Pantalla Completa',
  SidebarOpen: 'Barra Lateral Abierta',
  SidebarClose: 'Barra Lateral Cerrada',
  PanelLeft: 'Panel Izquierdo',
  PanelRight: 'Panel Derecho',
  PanelTop: 'Panel Superior',
  PanelBottom: 'Panel Inferior',

  // Acciones y Edición
  Plus: 'Más',
  Minus: 'Menos',
  Edit: 'Editar',
  Edit2: 'Editar 2',
  Edit3: 'Editar 3',
  Pencil: 'Lápiz',
  PenTool: 'Pluma',
  Save: 'Guardar',
  Trash: 'Eliminar',
  Trash2: 'Papelera',
  Delete: 'Borrar',
  Copy: 'Copiar',
  Clipboard: 'Portapapeles',
  ClipboardCopy: 'Copiar al Portapapeles',
  ClipboardCheck: 'Portapapeles Verificado',
  ClipboardList: 'Lista Portapapeles',
  Check: 'Verificar',
  CheckCircle: 'Verificado',
  CheckCircle2: 'Verificado 2',
  CheckSquare: 'Casilla Marcada',
  XCircle: 'Cerrar Círculo',
  XSquare: 'Cerrar Cuadrado',
  Undo: 'Deshacer',
  Redo: 'Rehacer',
  RotateCw: 'Rotar Derecha',
  RotateCcw: 'Rotar Izquierda',
  RefreshCw: 'Actualizar',
  RefreshCcw: 'Actualizar Inverso',
  Download: 'Descargar',
  Upload: 'Subir',
  Share: 'Compartir',
  Share2: 'Compartir 2',
  Forward: 'Reenviar',
  Reply: 'Responder',
  ReplyAll: 'Responder a Todos',
  Import: 'Importar',
  Export: 'Exportar',

  // Usuarios y Perfiles
  User: 'Usuario',
  Users: 'Usuarios',
  UserPlus: 'Agregar Usuario',
  UserMinus: 'Quitar Usuario',
  UserCheck: 'Usuario Verificado',
  UserX: 'Usuario Rechazado',
  UserCog: 'Configurar Usuario',
  Contact: 'Contacto',
  Smile: 'Sonrisa',
  Meh: 'Indiferente',
  Frown: 'Triste',
  Heart: 'Corazón',
  ThumbsUp: 'Me Gusta',
  ThumbsDown: 'No Me Gusta',
  Users2: 'Usuarios 2',
  UserCircle: 'Usuario Círculo',
  UserSquare: 'Usuario Cuadrado',

  // Comunicación
  Mail: 'Correo',
  MailOpen: 'Correo Abierto',
  Send: 'Enviar',
  MessageSquare: 'Mensaje',
  MessageCircle: 'Chat',
  Phone: 'Teléfono',
  PhoneCall: 'Llamada',
  PhoneIncoming: 'Llamada Entrante',
  PhoneOutgoing: 'Llamada Saliente',
  PhoneMissed: 'Llamada Perdida',
  PhoneForwarded: 'Llamada Reenviada',
  PhoneOff: 'Teléfono Apagado',
  Video: 'Video',
  VideoOff: 'Video Desactivado',
  Voicemail: 'Buzón de Voz',
  AtSign: 'Arroba',
  Inbox: 'Bandeja de Entrada',
  Mails: 'Correos',

  // Alertas y Notificaciones
  Bell: 'Notificación',
  BellOff: 'Notificaciones Desactivadas',
  BellRing: 'Campana Sonando',
  AlertCircle: 'Alerta Circular',
  AlertTriangle: 'Alerta',
  AlertOctagon: 'Alerta Octágono',
  Info: 'Información',
  HelpCircle: 'Ayuda',
  Ban: 'Prohibido',
  ShieldAlert: 'Escudo Alerta',
  ShieldCheck: 'Escudo Verificado',
  Shield: 'Escudo',
  ShieldOff: 'Escudo Desactivado',
  Siren: 'Sirena',

  // Archivos y Documentos
  File: 'Archivo',
  FileText: 'Documento',
  FilePlus: 'Agregar Archivo',
  FileMinus: 'Quitar Archivo',
  FileEdit: 'Editar Archivo',
  Files: 'Archivos',
  Folder: 'Carpeta',
  FolderPlus: 'Agregar Carpeta',
  FolderMinus: 'Quitar Carpeta',
  FolderOpen: 'Carpeta Abierta',
  Folders: 'Carpetas',
  FileArchive: 'Archivo Comprimido',
  FileCode: 'Código',
  FileJson: 'Archivo JSON',
  FileSpreadsheet: 'Hoja de Cálculo',
  FileImage: 'Imagen',
  FileVideo: 'Video',
  FileAudio: 'Audio',
  FilePdf: 'PDF',
  FileType: 'Tipo de Archivo',
  FileX: 'Archivo Eliminado',
  FileCheck: 'Archivo Verificado',
  FolderX: 'Carpeta Eliminada',
  FolderCheck: 'Carpeta Verificada',

  // Multimedia
  Image: 'Imagen',
  Images: 'Imágenes',
  Camera: 'Cámara',
  CameraOff: 'Cámara Desactivada',
  Music: 'Música',
  Play: 'Reproducir',
  Pause: 'Pausar',
  Square: 'Cuadrado',
  Circle: 'Círculo',
  SkipBack: 'Retroceder',
  SkipForward: 'Avanzar',
  FastForward: 'Avance Rápido',
  Rewind: 'Rebobinar',
  Volume: 'Volumen',
  Volume1: 'Volumen Bajo',
  Volume2: 'Volumen Alto',
  VolumeX: 'Sin Volumen',
  Mic: 'Micrófono',
  MicOff: 'Micrófono Desactivado',
  Film: 'Película',
  PlayCircle: 'Reproducir Círculo',
  PauseCircle: 'Pausar Círculo',
  StopCircle: 'Detener Círculo',

  // Comercio y Finanzas
  ShoppingCart: 'Carrito',
  ShoppingBag: 'Bolsa de Compras',
  CreditCard: 'Tarjeta de Crédito',
  Wallet: 'Cartera',
  DollarSign: 'Dólar',
  Euro: 'Euro',
  Percent: 'Porcentaje',
  Tag: 'Etiqueta',
  Tags: 'Etiquetas',
  Receipt: 'Recibo',
  Banknote: 'Billete',
  Package: 'Paquete',
  Package2: 'Paquete 2',
  PackageCheck: 'Paquete Verificado',
  PackageX: 'Paquete Rechazado',
  PackagePlus: 'Agregar Paquete',
  PackageMinus: 'Quitar Paquete',
  Gift: 'Regalo',
  Award: 'Premio',
  TrendingUp: 'Tendencia Alcista',
  TrendingDown: 'Tendencia Bajista',
  BarChart: 'Gráfico de Barras',
  BarChart2: 'Gráfico de Barras 2',
  BarChart3: 'Gráfico de Barras 3',
  LineChart: 'Gráfico de Líneas',
  PieChart: 'Gráfico Circular',
  Activity: 'Actividad',
  Calculator: 'Calculadora',
  Coins: 'Monedas',

  // Tiempo y Calendario
  Calendar: 'Calendario',
  CalendarDays: 'Días del Calendario',
  CalendarCheck: 'Calendario Verificado',
  CalendarX: 'Calendario Cancelado',
  CalendarPlus: 'Agregar al Calendario',
  CalendarMinus: 'Quitar del Calendario',
  Clock: 'Reloj',
  Clock1: 'Reloj 1',
  Clock2: 'Reloj 2',
  Clock3: 'Reloj 3',
  Clock4: 'Reloj 4',
  Clock5: 'Reloj 5',
  Clock6: 'Reloj 6',
  Clock7: 'Reloj 7',
  Clock8: 'Reloj 8',
  Clock9: 'Reloj 9',
  Clock10: 'Reloj 10',
  Clock11: 'Reloj 11',
  Clock12: 'Reloj 12',
  Timer: 'Temporizador',
  TimerOff: 'Temporizador Desactivado',
  Hourglass: 'Reloj de Arena',
  AlarmClock: 'Despertador',
  CalendarRange: 'Rango de Calendario',

  // Ubicación y Mapas
  MapPin: 'Ubicación',
  Map: 'Mapa',
  Navigation2: 'Navegación 2',
  Globe: 'Globo',
  Globe2: 'Globo 2',
  Milestone: 'Hito',
  Flag: 'Bandera',
  FlagTriangleRight: 'Bandera Triangular',
  Locate: 'Localizar',
  LocateFixed: 'Ubicación Fija',
  LocateOff: 'Localización Desactivada',
  Route: 'Ruta',
  Signpost: 'Señal',

  // Dispositivos y Tecnología
  Laptop: 'Portátil',
  Monitor: 'Monitor',
  Smartphone: 'Teléfono Inteligente',
  Tablet: 'Tableta',
  Watch: 'Reloj',
  Tv: 'Televisión',
  Speaker: 'Altavoz',
  Headphones: 'Auriculares',
  Mouse: 'Ratón',
  Keyboard: 'Teclado',
  Printer: 'Impresora',
  HardDrive: 'Disco Duro',
  Server: 'Servidor',
  Database: 'Base de Datos',
  Cpu: 'Procesador',
  Battery: 'Batería',
  BatteryCharging: 'Batería Cargando',
  BatteryFull: 'Batería Llena',
  BatteryLow: 'Batería Baja',
  BatteryMedium: 'Batería Media',
  BatteryWarning: 'Batería Advertencia',
  Wifi: 'WiFi',
  WifiOff: 'WiFi Desactivado',
  Bluetooth: 'Bluetooth',
  BluetoothConnected: 'Bluetooth Conectado',
  BluetoothOff: 'Bluetooth Desactivado',
  Cast: 'Transmitir',
  Usb: 'USB',
  Power: 'Encender',
  PowerOff: 'Apagar',
  Plug: 'Enchufe',
  Zap: 'Rayo',
  ZapOff: 'Rayo Desactivado',
  MonitorSpeaker: 'Monitor con Altavoz',
  Gamepad: 'Mando de Juego',
  Gamepad2: 'Mando de Juego 2',

  // Desarrollo y Código
  Code: 'Código',
  Code2: 'Código 2',
  Terminal: 'Terminal',
  Command: 'Comando',
  GitBranch: 'Rama Git',
  GitCommit: 'Commit Git',
  GitMerge: 'Fusionar Git',
  GitPullRequest: 'Pull Request',
  Github: 'GitHub',
  Gitlab: 'GitLab',
  Bug: 'Error',
  Wrench: 'Llave Inglesa',
  Hammer: 'Martillo',
  Sliders: 'Controles',
  SlidersHorizontal: 'Controles Horizontales',
  Construction: 'Construcción',
  Binary: 'Binario',
  Braces: 'Llaves',
  Brackets: 'Corchetes',

  // Seguridad
  Lock: 'Bloqueado',
  LockOpen: 'Abierto',
  Unlock: 'Desbloqueado',
  Key: 'Llave',
  KeyRound: 'Llave Redonda',
  Eye: 'Ver',
  EyeOff: 'Ocultar',
  Fingerprint: 'Huella Digital',
  Scan: 'Escanear',
  ScanLine: 'Línea de Escaneo',
  ShieldX: 'Escudo Rechazado',
  KeySquare: 'Llave Cuadrada',

  // Organización y Layout
  Grid: 'Cuadrícula',
  Grid2x2: 'Cuadrícula 2x2',
  Grid3x3: 'Cuadrícula 3x3',
  List: 'Lista',
  LayoutGrid: 'Diseño Cuadrícula',
  LayoutList: 'Diseño Lista',
  LayoutDashboard: 'Panel de Control',
  LayoutTemplate: 'Plantilla',
  Columns: 'Columnas',
  Rows: 'Filas',
  Table: 'Tabla',
  Table2: 'Tabla 2',
  Sidebar: 'Barra Lateral',
  AlignLeft: 'Alinear Izquierda',
  AlignCenter: 'Alinear Centro',
  AlignRight: 'Alinear Derecha',
  AlignJustify: 'Justificar',

  // Ordenamiento y Filtros
  Filter: 'Filtro',
  FilterX: 'Quitar Filtro',
  SortAsc: 'Ordenar Ascendente',
  SortDesc: 'Ordenar Descendente',
  ArrowUpDown: 'Ordenar',
  ArrowDownUp: 'Ordenar Inverso',
  MoveUp: 'Mover Arriba',
  MoveDown: 'Mover Abajo',
  MoveLeft: 'Mover Izquierda',
  MoveRight: 'Mover Derecha',
  Move3d: 'Mover 3D',
  Shuffle: 'Mezclar',

  // Marcadores y Favoritos
  Star: 'Estrella',
  Bookmark: 'Marcador',
  BookmarkPlus: 'Agregar Marcador',
  BookmarkMinus: 'Quitar Marcador',
  BookOpen: 'Libro Abierto',
  Book: 'Libro',
  Library: 'Biblioteca',
  StarHalf: 'Media Estrella',
  StarOff: 'Sin Estrella',

  // Conectividad y Enlaces
  Link: 'Enlace',
  Link2: 'Enlace 2',
  ExternalLink: 'Enlace Externo',
  Unlink: 'Desvincular',
  Paperclip: 'Clip',
  Anchor: 'Ancla',
  Chain: 'Cadena',
  Unplug: 'Desconectar',

  // Clima
  Sun: 'Sol',
  Moon: 'Luna',
  Cloud: 'Nube',
  CloudRain: 'Lluvia',
  CloudSnow: 'Nieve',
  CloudDrizzle: 'Llovizna',
  CloudLightning: 'Tormenta',
  CloudFog: 'Niebla',
  CloudOff: 'Sin Nubes',
  Sunrise: 'Amanecer',
  Sunset: 'Atardecer',
  Thermometer: 'Termómetro',
  ThermometerSun: 'Termómetro Sol',
  ThermometerSnowflake: 'Termómetro Frío',
  Snowflake: 'Copo de Nieve',
  Wind: 'Viento',
  Droplet: 'Gota',
  Droplets: 'Gotas',
  Umbrella: 'Paraguas',
  Rainbow: 'Arcoíris',
  Tornado: 'Tornado',

  // Transporte
  Car: 'Automóvil',
  Truck: 'Camión',
  Bus: 'Autobús',
  Bike: 'Bicicleta',
  Plane: 'Avión',
  PlaneTakeoff: 'Despegue',
  PlaneLanding: 'Aterrizaje',
  Ship: 'Barco',
  Train: 'Tren',
  Rocket: 'Cohete',
  Fuel: 'Combustible',
  CarFront: 'Frente del Coche',
  Ambulance: 'Ambulancia',
  Taxi: 'Taxi',

  // Edificios y Lugares
  Building: 'Edificio',
  Building2: 'Edificio 2',
  Factory: 'Fábrica',
  Warehouse: 'Almacén',
  Store: 'Tienda',
  Hotel: 'Hotel',
  Church: 'Iglesia',
  School: 'Escuela',
  Hospital: 'Hospital',
  TreePine: 'Pino',
  Trees: 'Árboles',
  Tent: 'Tienda de Campaña',
  Castle: 'Castillo',
  Landmark: 'Monumento',

  // Comida y Bebida
  Coffee: 'Café',
  Beer: 'Cerveza',
  Wine: 'Vino',
  Pizza: 'Pizza',
  Cake: 'Pastel',
  Apple: 'Manzana',
  Salad: 'Ensalada',
  Utensils: 'Cubiertos',
  UtensilsCrossed: 'Cubiertos Cruzados',
  CupSoda: 'Refresco',
  IceCream: 'Helado',
  Cherry: 'Cereza',
  Grape: 'Uva',
  Sandwich: 'Sándwich',

  // Formas y Símbolos
  Triangle: 'Triángulo',
  Pentagon: 'Pentágono',
  Hexagon: 'Hexágono',
  Octagon: 'Octágono',
  Diamond: 'Diamante',
  Hash: 'Numeral',
  Asterisk: 'Asterisco',
  Equal: 'Igual',
  Infinity: 'Infinito',
  Shapes: 'Formas',

  // Herramientas
  Briefcase: 'Maletín',
  Tool: 'Herramienta',
  Paintbrush: 'Pincel',
  Pipette: 'Cuentagotas',
  Eraser: 'Borrador',
  Scissors: 'Tijeras',
  Ruler: 'Regla',
  Magnet: 'Imán',
  Drill: 'Taladro',
  Saw: 'Sierra',
  Screwdriver: 'Destornillador',
  Spanner: 'Llave Inglesa',

  // Salud y Médico
  HeartPulse: 'Pulso',
  Stethoscope: 'Estetoscopio',
  Syringe: 'Jeringa',
  Pill: 'Pastilla',
  Bandage: 'Vendaje',
  Cross: 'Cruz',
  Dna: 'ADN',

  // Accesibilidad
  Accessibility: 'Accesibilidad',
  EarOff: 'Oído Desactivado',
  Ear: 'Oído',
  Focus: 'Enfoque',
  Glasses: 'Gafas',
  Contrast: 'Contraste',

  // Deportes y Actividades
  Dumbbell: 'Mancuerna',
  Football: 'Fútbol',
  Trophy: 'Trofeo',
  Medal: 'Medalla',
  Target: 'Objetivo',
  Flame: 'Fuego',

  // Naturaleza
  Leaf: 'Hoja',
  Flower: 'Flor',
  Flower2: 'Flor 2',
  Fish: 'Pez',
  Bird: 'Pájaro',
  Rabbit: 'Conejo',
  Squirrel: 'Ardilla',

  // Texto y Tipografía
  Type: 'Tipo',
  Bold: 'Negrita',
  Italic: 'Cursiva',
  Underline: 'Subrayado',
  Strikethrough: 'Tachado',
  Subscript: 'Subíndice',
  Superscript: 'Superíndice',
  Quote: 'Cita',
  Text: 'Texto',
  TextCursor: 'Cursor de Texto',
  TextSelect: 'Seleccionar Texto',
  Heading: 'Encabezado',
  Heading1: 'Encabezado 1',
  Heading2: 'Encabezado 2',
  Heading3: 'Encabezado 3',
  Heading4: 'Encabezado 4',
  Heading5: 'Encabezado 5',
  Heading6: 'Encabezado 6',
  Paragraph: 'Párrafo',
  CaseSensitive: 'Sensible a Mayúsculas',
  CaseUpper: 'Mayúsculas',
  CaseLower: 'Minúsculas',
  RemoveFormatting: 'Quitar Formato',
  WrapText: 'Ajustar Texto',
  IndentIncrease: 'Aumentar Sangría',
  IndentDecrease: 'Disminuir Sangría',
  ListOrdered: 'Lista Ordenada',
  ListUnordered: 'Lista No Ordenada',
  ListChecks: 'Lista de Verificación',
  ListX: 'Lista Cancelada',
  ListPlus: 'Agregar a Lista',
  ListMinus: 'Quitar de Lista',
  ListStart: 'Inicio de Lista',
  ListEnd: 'Fin de Lista',
  ListRestart: 'Reiniciar Lista',
  ListTree: 'Lista de Árbol',
  ListVideo: 'Lista de Videos',
  ListMusic: 'Lista de Música',
  ListFilter: 'Filtrar Lista',

  // Matemáticas y Números
  Divide: 'Dividir',
  NotEqual: 'No Igual',
  GreaterThan: 'Mayor Que',
  LessThan: 'Menor Que',
  GreaterThanEqual: 'Mayor o Igual',
  LessThanEqual: 'Menor o Igual',
  PlusCircle: 'Más Círculo',
  MinusCircle: 'Menos Círculo',
  DivideCircle: 'Dividir Círculo',
  EqualNot: 'No Igual',
  Sigma: 'Sigma',
  Pi: 'Pi',
  Radical: 'Radical',
  Function: 'Función',
  Variable: 'Variable',

  // Redes Sociales y Comunicación
  Facebook: 'Facebook',
  Twitter: 'Twitter',
  Instagram: 'Instagram',
  Linkedin: 'LinkedIn',
  Youtube: 'YouTube',
  Twitch: 'Twitch',
  Discord: 'Discord',
  Slack: 'Slack',
  MessagesSquare: 'Mensajes Cuadrados',
  Speech: 'Habla',
  Mention: 'Mención',
  SendHorizontal: 'Enviar Horizontal',
  Megaphone: 'Megáfono',
  VolumeOff: 'Volumen Apagado',
  Podcast: 'Podcast',

  // Juegos y Entretenimiento
  Joystick: 'Joystick',
  Spade: 'Pica',
  Club: 'Trébol',
  Puzzle: 'Rompecabezas',
  Crosshair: 'Punto de Mira',
  Ribbon: 'Cinta',
  PartyPopper: 'Confeti',
  Sparkle: 'Destello',
  Stars: 'Estrellas',
  Magic: 'Magia',

  // Ciencia y Educación
  GraduationCap: 'Birrete',
  BookMarked: 'Libro Marcado',
  BookmarkCheck: 'Marcador Verificado',
  BookmarkX: 'Marcador Eliminado',
  University: 'Universidad',
  Microscope: 'Microscopio',
  TestTube: 'Tubo de Ensayo',
  TestTubes: 'Tubos de Ensayo',
  FlaskConical: 'Matraz Cónico',
  FlaskRound: 'Matraz Redondo',
  Beaker: 'Vaso de Precipitados',
  Atom: 'Átomo',
  Molecule: 'Molécula',
  Orbit: 'Órbita',
  Telescope: 'Telescopio',
  Earth: 'Tierra',
  Comet: 'Cometa',
  Satellite: 'Satélite',
  SatelliteDish: 'Antena Parabólica',

  // Herramientas de Diseño
  Paintbrush2: 'Pincel 2',
  PaintBucket: 'Balde de Pintura',
  Eyedropper: 'Cuentagotas',
  ColorWheel: 'Rueda de Color',
  Brightness: 'Brillo',
  BrightnessUp: 'Aumentar Brillo',
  BrightnessDown: 'Disminuir Brillo',
  Layers: 'Capas',
  Layers2: 'Capas 2',
  Layers3: 'Capas 3',
  Group: 'Agrupar',
  Ungroup: 'Desagrupar',
  Combine: 'Combinar',
  Intersect: 'Intersectar',
  Union: 'Unión',
  Exclude: 'Excluir',
  Subtract: 'Sustraer',
  Crop: 'Recortar',
  FlipHorizontal: 'Voltear Horizontal',
  FlipVertical: 'Voltear Vertical',
  Scale: 'Escalar',
  Resize: 'Redimensionar',
  Aspect: 'Aspecto',

  // Medios y Streaming
  MicVocal: 'Micrófono Vocal',
  AudioLines: 'Líneas de Audio',
  AudioWaveform: 'Forma de Onda',
  Music2: 'Música 2',
  Music3: 'Música 3',
  Music4: 'Música 4',
  Disc: 'Disco',
  Disc2: 'Disco 2',
  Disc3: 'Disco 3',
  DiscAlbum: 'Álbum',
  Cassette: 'Casete',
  Vinyl: 'Vinilo',
  Antenna: 'Antena',
  Signal: 'Señal',
  SignalHigh: 'Señal Alta',
  SignalLow: 'Señal Baja',
  SignalMedium: 'Señal Media',
  SignalZero: 'Sin Señal',
  WifiHigh: 'WiFi Alto',
  WifiLow: 'WiFi Bajo',
  Airplay: 'AirPlay',
  Chromecast: 'Chromecast',
  Tv2: 'TV 2',
  MonitorPlay: 'Monitor Reproducir',
  Projector: 'Proyector',
  Presentation: 'Presentación',

  // Navegación Web
  History: 'Historial',
  SearchCheck: 'Buscar Verificado',
  SearchCode: 'Buscar Código',
  SearchSlash: 'Buscar Barra',
  SearchX: 'Buscar Cancelar',

  // Estados y Indicadores
  QuestionMark: 'Signo de Interrogación',
  Loader: 'Cargador',
  Loader2: 'Cargador 2',
  LoaderCircle: 'Cargador Circular',
  Spinner: 'Giratorio',
  Ellipsis: 'Puntos Suspensivos',
  EllipsisVertical: 'Puntos Suspensivos Verticales',
  Dot: 'Punto',
  CircleEllipsis: 'Círculo con Puntos',
  SquareDot: 'Cuadrado con Punto',
  HeartOff: 'Corazón Apagado',
  HeartHandshake: 'Corazón Apretón',
  HeartCrack: 'Corazón Roto',
  Laugh: 'Risa',
  Angry: 'Enojado',
  Surprised: 'Sorprendido',

  // Otros
  Sparkles: 'Destellos',
  Lightbulb: 'Bombilla',
  Crown: 'Corona',
  Radio: 'Radio',
  Rss: 'RSS',
  QrCode: 'Código QR',
  Barcode: 'Código de Barras',
  ScanBarcode: 'Escanear Código',
  CircleDot: 'Punto Circular',
  Gauge: 'Indicador',
  Palette: 'Paleta',
  Brush: 'Brocha',
  Wand: 'Varita',
  Wand2: 'Varita 2',
  Dice1: 'Dado 1',
  Dice2: 'Dado 2',
  Dice3: 'Dado 3',
  Dice4: 'Dado 4',
  Dice5: 'Dado 5',
  Dice6: 'Dado 6',
  Gem: 'Gema',
  PiggyBank: 'Alcancía',
  Vault: 'Bóveda',
  Safe: 'Caja Fuerte',
  Verified: 'Verificado',
  BadgeCheck: 'Insignia Verificada',
  Badge: 'Insignia',
  BadgeAlert: 'Insignia Alerta',
  BadgeX: 'Insignia Cancelada',
  BadgeHelp: 'Insignia Ayuda',
  BadgeInfo: 'Insignia Información',
  BadgePlus: 'Insignia Más',
  BadgeMinus: 'Insignia Menos',
  BadgeDollarSign: 'Insignia Dólar',
  BadgePercent: 'Insignia Porcentaje',
}

// Función para obtener el componente de icono por nombre
export const getIconComponent = (iconName: string) => {
  return (LucideIcons as any)[iconName] || null
}

// Función para verificar si un icono existe
export const isValidIcon = (iconName: string): boolean => {
  return availableIcons.includes(iconName as IconName)
}

// Función para obtener el label en español de un icono
export const getIconLabel = (iconName: string): string => {
  return iconLabelsES[iconName as IconName] || iconName
}

// Función para buscar iconos por label en español o nombre en inglés
export const searchIcons = (searchTerm: string): IconName[] => {
  if (!searchTerm) return [...availableIcons]

  const term = searchTerm.toLowerCase()
  return availableIcons.filter((iconName) => {
    const label = iconLabelsES[iconName].toLowerCase()
    const name = iconName.toLowerCase()
    return label.includes(term) || name.includes(term)
  })
}
