export const LABELS = {
  powerSupply: {
    ac_electric: 'Eléctrica AC',
    battery: 'Batería',
    rechargeable_battery: 'Batería Recargable',
    internal_battery: 'Batería Interna',
    mixed: 'Mixta',
    usb: 'USB',
    eliminator: 'Eliminador',
    none: 'Ninguna',
  },
  connectivity: {
    usb: 'USB',
    rs232: 'RS-232',
    wifi: 'WiFi',
    ethernet: 'Ethernet',
    bluetooth: 'Bluetooth',
    data_cable: 'Cable de Datos',
  },
  material: {
    stainless_steel: 'Acero Inoxidable',
    aluminum: 'Aluminio',
    steel: 'Acero',
    plastic: 'Plástico',
    adaptable: 'Adaptable',
    stainless_steel_coating: 'Recubrimiento Acero Inoxidable',
  },
  displayType: {
    lcd_backlit: 'LCD Retroiluminado',
    led_high_visibility: 'LED Alta Visibilidad',
    lcd_green: 'LCD Verde',
    double_red: 'Doble Rojo',
    led_red_tower: 'Torre LED Roja',
    led_6_digits: 'LED 6 Dígitos',
  },
  platformType: {
    standard_plate: 'Plato Estándar',
    heavy_duty_wheels: 'Ruedas Trabajo Pesado',
    platform_pedestal: 'Plataforma con Pedestal',
  },
  capacityType: {
    multirange: 'Multirango',
    single_range: 'Rango Único',
    configurable: 'Configurable',
  },
  consumableType: {
    charger_eliminator: 'Cargador/Eliminador',
    battery: 'Batería',
    cable: 'Cable',
    accessory: 'Accesorio',
    spare_part: 'Repuesto',
  },
  certifications: {
    ce: 'CE',
    fcc: 'FCC',
    ul: 'UL',
    rohs: 'RoHS',
  },
  productType: {
    scale: 'Báscula',
    consumable: 'Consumible',
    accessory: 'Accesorio',
    software: 'Software',
    service: 'Servicio',
    equipment: 'Equipo',
    tool: 'Herramienta',
    part: 'Repuesto',
  },
} as const
