/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    products: Product;
    brands: Brand;
    models: Model;
    suppliers: Supplier;
    clients: Client;
    services: Service;
    manuals: Manual;
    forms: Form;
    'form-submissions': FormSubmission;
    redirects: Redirect;
    search: Search;
    exports: Export;
    'activity-log': ActivityLog;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    models: ModelsSelect<false> | ModelsSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    manuals: ManualsSelect<false> | ManualsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    'activity-log': ActivityLogSelect<false> | ActivityLogSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
    chatbot: Chatbot;
    coupons: Coupon;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    chatbot: ChatbotSelect<false> | ChatbotSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Administra las páginas del sitio: crea, edita y elimina páginas
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  content: {
    layout: (
      | CallToActionBlock
      | ContentBlock
      | MediaBlock
      | FormBlock
      | FAQBlock
      | PostArchiveBlock
      | ServiceArchiveBlock
    )[];
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug: string;
  slugLock?: boolean | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  /**
   * Select the style variant for the CTA section
   */
  variant: 'default' | 'section-3' | 'section-5' | 'section-6' | 'section-7';
  /**
   * Small text above the headline (e.g., "CTA Section")
   */
  label?: string | null;
  /**
   * Main headline text (will be displayed large)
   */
  headline: string;
  /**
   * Additional content below the headline
   */
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Image displayed alongside the CTA content
   */
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * Administra los archivos del sitio: crea, edita y elimina archivos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Administra los usuarios del sitio: crea, edita y elimina usuarios
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  firstName: string;
  lastName?: string | null;
  avatar?: (number | null) | Media;
  roles?: ('admin' | 'editor' | 'user')[] | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  /**
   * Add columns to create your layout. Each column can have different sizes and content.
   */
  columns?:
    | {
        /**
         * Choose the width of this column
         */
        size?: ('small' | 'medium' | 'large' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * Crea y gestiona formularios personalizados para tu sitio web.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  /**
   * Nombre descriptivo del formulario
   */
  title: string;
  /**
   * Define los campos que aparecerán en el formulario
   */
  fields?:
    | (
        | TextFormField
        | TextareaFormField
        | EmailFormField
        | NumberFormField
        | SelectFormField
        | CheckboxFormField
        | CountryFormField
        | StateFormField
        | MessageFormField
      )[]
    | null;
  /**
   * Configura qué sucede cuando se envía el formulario
   */
  submitConfig: {
    buttonLabel: string;
    confirmationType?: ('message' | 'redirect') | null;
    /**
     * Mensaje que se muestra después de enviar el formulario
     */
    confirmationMessage?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Página a la que se redirige después de enviar
     */
    redirectPage?: (number | null) | Page;
  };
  /**
   * Configura los emails que se enviarán cuando alguien complete el formulario. Usa {{nombreCampo}} para insertar valores del formulario.
   */
  emailNotifications?:
    | {
        /**
         * Direcciones separadas por comas
         */
        emailTo: string;
        /**
         * Email del remitente
         */
        emailFrom?: string | null;
        /**
         * Copia visible
         */
        cc?: string | null;
        /**
         * Copia oculta
         */
        bcc?: string | null;
        /**
         * Email para respuestas
         */
        replyTo?: string | null;
        /**
         * Usa {{nombreCampo}} para valores dinámicos
         */
        subject: string;
        /**
         * Usa {{nombreCampo}} para valores dinámicos, {{*}} para todos los datos, o {{*:tabla}} para formato tabla HTML
         */
        message: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Desactiva el formulario para dejar de recibir envíos
   */
  active?: boolean | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextFormField".
 */
export interface TextFormField {
  /**
   * Identificador único (sin espacios)
   */
  name: string;
  label: string;
  width?: number | null;
  required?: boolean | null;
  defaultValue?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextareaFormField".
 */
export interface TextareaFormField {
  name: string;
  label: string;
  width?: number | null;
  required?: boolean | null;
  defaultValue?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textarea';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailFormField".
 */
export interface EmailFormField {
  name: string;
  label: string;
  width?: number | null;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'email';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NumberFormField".
 */
export interface NumberFormField {
  name: string;
  label: string;
  width?: number | null;
  required?: boolean | null;
  defaultValue?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'number';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SelectFormField".
 */
export interface SelectFormField {
  name: string;
  label: string;
  width?: number | null;
  required?: boolean | null;
  options?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  defaultValue?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'select';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CheckboxFormField".
 */
export interface CheckboxFormField {
  name: string;
  label: string;
  width?: number | null;
  required?: boolean | null;
  defaultValue?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'checkbox';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CountryFormField".
 */
export interface CountryFormField {
  name: string;
  label: string;
  width?: number | null;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'country';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StateFormField".
 */
export interface StateFormField {
  name: string;
  label: string;
  width?: number | null;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'state';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MessageFormField".
 */
export interface MessageFormField {
  message: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'message';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  faqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostArchiveBlock".
 */
export interface PostArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'post-archive';
}
/**
 * Administra las categorías del sitio: crea, edita y elimina categorías
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  slugLock?: boolean | null;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Administra las publicaciones del blog: crea, edita y elimina artículos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug: string;
  slugLock?: boolean | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceArchiveBlock".
 */
export interface ServiceArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'services' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'service-archive';
}
/**
 * Administra los productos del sitio: crea, edita y elimina artículos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * La marca es el fabricante del producto
   */
  brand: number | Brand;
  model: number | Model;
  /**
   * Los proveedores son las empresas que suministran el producto
   */
  supplier?: (number | Supplier)[] | null;
  /**
   * La garantía es el periodo de tiempo que se ofrece por el producto
   */
  warranty?: string | null;
  type?: ('general' | 'scale') | null;
  /**
   * Puede ser una categoria general o por ejemplo "Basculas Comerciales", "Cargadores", etc.
   */
  categories?: (number | Category)[] | null;
  heroImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug: string;
  slugLock?: boolean | null;
  price?: number | null;
  discount?: number | null;
  /**
   * Se aplica el 16% de IVA al precio final
   */
  iva?: boolean | null;
  total?: number | null;
  stock: number;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Administra las marcas del sitio: crea, edita y elimina marcas
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  title: string;
  /**
   * La imagen debe de tener la extension .svg para tener la mejor calidad posible
   */
  heroImage?: (number | null) | Media;
  slug: string;
  slugLock?: boolean | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models".
 */
export interface Model {
  id: number;
  title: string;
  brand: number | Brand;
  slug: string;
  slugLock?: boolean | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Administra los proveedores del sitio: crea, edita y elimina proveedores
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: number;
  title: string;
  companyName?: string | null;
  heroImage?: (number | null) | Media;
  brands?: (number | Brand)[] | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contact?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  website?: string | null;
  slug: string;
  slugLock?: boolean | null;
  credit?: string | null;
  discount?: number | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Administra los clientes del sitio: crea, edita y elimina clientes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  title: string;
  companyName?: string | null;
  heroImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contact?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  website?: string | null;
  slug: string;
  slugLock?: boolean | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Administra los servicios del sitio: crea, edita y elimina artículos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  heroImage: number | Media;
  relatedServices?: (number | Service)[] | null;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug: string;
  slugLock?: boolean | null;
  price?: number | null;
  discount?: number | null;
  /**
   * Se aplica el 16% de IVA al precio final
   */
  iva?: boolean | null;
  total?: number | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Administra las publicaciones del blog: crea, edita y elimina artículos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manuals".
 */
export interface Manual {
  id: number;
  title: string;
  heroImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedManuals?: (number | Manual)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug: string;
  slugLock?: boolean | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Registro de todos los envíos de formularios recibidos. Los datos se guardan automáticamente cuando un usuario completa un formulario.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Esta es una colección de redirecciones de URL que se crean en el CMS. Estas redirecciones son utilizadas por el sitio web.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Necesitará reconstruir el sitio web cuando cambie este campo.
   */
  from: string;
  /**
   * Necesitará reconstruir el sitio web cuando cambie este campo.
   */
  to?: {
    /**
     * Seleccione si desea redirigir a una URL interna o externa.
     */
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null);
    url?: string | null;
  };
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Esta es una colección de resultados de búsqueda generados automáticamente. Estos resultados son utilizados por la búsqueda global del sitio y se actualizan automáticamente a medida que se crean o actualizan documentos en el CMS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'products';
        value: number | Product;
      }
    | {
        relationTo: 'manuals';
        value: number | Manual;
      }
    | {
        relationTo: 'services';
        value: number | Service;
      };
  slug?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format?: ('csv' | 'json') | null;
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Esta es una colección de logs de actividad generados automáticamente. Estos logs son utilizados por el sistema para rastrear las acciones realizadas por los usuarios en el CMS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-log".
 */
export interface ActivityLog {
  id: number;
  user?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  operation?: ('create' | 'read' | 'update' | 'delete') | null;
  timestamp?: string | null;
  ipAddress?: string | null;
  deviceInfo?: string | null;
  locale?: string | null;
  resource?: string | null;
  documentId?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'models';
        value: number | Model;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: number | Supplier;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'manuals';
        value: number | Manual;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'exports';
        value: number | Export;
      } | null)
    | ({
        relationTo: 'activity-log';
        value: number | ActivityLog;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?:
    | T
    | {
        layout?:
          | T
          | {
              cta?: T | CallToActionBlockSelect<T>;
              content?: T | ContentBlockSelect<T>;
              mediaBlock?: T | MediaBlockSelect<T>;
              formBlock?: T | FormBlockSelect<T>;
              faq?: T | FAQBlockSelect<T>;
              'post-archive'?: T | PostArchiveBlockSelect<T>;
              'service-archive'?: T | ServiceArchiveBlockSelect<T>;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  variant?: T;
  label?: T;
  headline?: T;
  content?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostArchiveBlock_select".
 */
export interface PostArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceArchiveBlock_select".
 */
export interface ServiceArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  content?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  firstName?: T;
  lastName?: T;
  avatar?: T;
  roles?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  brand?: T;
  model?: T;
  supplier?: T;
  warranty?: T;
  type?: T;
  categories?: T;
  heroImage?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  price?: T;
  discount?: T;
  iva?: T;
  total?: T;
  stock?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  slug?: T;
  slugLock?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models_select".
 */
export interface ModelsSelect<T extends boolean = true> {
  title?: T;
  brand?: T;
  slug?: T;
  slugLock?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  title?: T;
  companyName?: T;
  heroImage?: T;
  brands?: T;
  content?: T;
  contact?: T;
  email?: T;
  phone?: T;
  address?: T;
  website?: T;
  slug?: T;
  slugLock?: T;
  credit?: T;
  discount?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  title?: T;
  companyName?: T;
  heroImage?: T;
  content?: T;
  contact?: T;
  email?: T;
  phone?: T;
  address?: T;
  website?: T;
  slug?: T;
  slugLock?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  relatedServices?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  price?: T;
  discount?: T;
  iva?: T;
  total?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manuals_select".
 */
export interface ManualsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedManuals?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        text?: T | TextFormFieldSelect<T>;
        textarea?: T | TextareaFormFieldSelect<T>;
        email?: T | EmailFormFieldSelect<T>;
        number?: T | NumberFormFieldSelect<T>;
        select?: T | SelectFormFieldSelect<T>;
        checkbox?: T | CheckboxFormFieldSelect<T>;
        country?: T | CountryFormFieldSelect<T>;
        state?: T | StateFormFieldSelect<T>;
        message?: T | MessageFormFieldSelect<T>;
      };
  submitConfig?:
    | T
    | {
        buttonLabel?: T;
        confirmationType?: T;
        confirmationMessage?: T;
        redirectPage?: T;
      };
  emailNotifications?:
    | T
    | {
        emailTo?: T;
        emailFrom?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  active?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextFormField_select".
 */
export interface TextFormFieldSelect<T extends boolean = true> {
  name?: T;
  label?: T;
  width?: T;
  required?: T;
  defaultValue?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextareaFormField_select".
 */
export interface TextareaFormFieldSelect<T extends boolean = true> {
  name?: T;
  label?: T;
  width?: T;
  required?: T;
  defaultValue?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailFormField_select".
 */
export interface EmailFormFieldSelect<T extends boolean = true> {
  name?: T;
  label?: T;
  width?: T;
  required?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NumberFormField_select".
 */
export interface NumberFormFieldSelect<T extends boolean = true> {
  name?: T;
  label?: T;
  width?: T;
  required?: T;
  defaultValue?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SelectFormField_select".
 */
export interface SelectFormFieldSelect<T extends boolean = true> {
  name?: T;
  label?: T;
  width?: T;
  required?: T;
  options?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  defaultValue?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CheckboxFormField_select".
 */
export interface CheckboxFormFieldSelect<T extends boolean = true> {
  name?: T;
  label?: T;
  width?: T;
  required?: T;
  defaultValue?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CountryFormField_select".
 */
export interface CountryFormFieldSelect<T extends boolean = true> {
  name?: T;
  label?: T;
  width?: T;
  required?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StateFormField_select".
 */
export interface StateFormFieldSelect<T extends boolean = true> {
  name?: T;
  label?: T;
  width?: T;
  required?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MessageFormField_select".
 */
export interface MessageFormFieldSelect<T extends boolean = true> {
  message?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  content?: T;
  heroImage?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-log_select".
 */
export interface ActivityLogSelect<T extends boolean = true> {
  user?: T;
  operation?: T;
  timestamp?: T;
  ipAddress?: T;
  deviceInfo?: T;
  locale?: T;
  resource?: T;
  documentId?: T;
  data?: T;
  createdBy?: T;
  lastModifiedBy?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Aquí se configura el encabezado global del sitio web con menús
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  productsMenu: {
    title: string;
    showInNav?: boolean | null;
    hasDropdown?: boolean | null;
    directLink?: {
      link: {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null);
        url?: string | null;
        label: string;
      };
    };
    items?:
      | {
          /**
           * Select an icon
           */
          icon?: string | null;
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  servicesMenu: {
    title: string;
    showInNav?: boolean | null;
    hasDropdown?: boolean | null;
    directLink?: {
      link: {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null);
        url?: string | null;
        label: string;
      };
    };
    items?:
      | {
          /**
           * Select an icon
           */
          icon?: string | null;
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  resourcesMenu: {
    title: string;
    showInNav?: boolean | null;
    hasDropdown?: boolean | null;
    directLink?: {
      link: {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null);
        url?: string | null;
        label: string;
      };
    };
    items?:
      | {
          /**
           * Select an icon
           */
          icon?: string | null;
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  companyMenu?: {
    title?: string | null;
    showInNav?: boolean | null;
    hasDropdown?: boolean | null;
    directLink?: {
      link: {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null);
        url?: string | null;
        label: string;
      };
    };
    items?:
      | {
          /**
           * Select an icon
           */
          icon?: string | null;
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  contactMenu?: {
    title?: string | null;
    showInNav?: boolean | null;
    hasDropdown?: boolean | null;
    directLink?: {
      link: {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null);
        url?: string | null;
        label: string;
      };
    };
    items?:
      | {
          /**
           * Select an icon
           */
          icon?: string | null;
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Aquí se configura el pie de página global del sitio web
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  productSection?: {
    title?: string | null;
    items?:
      | {
          /**
           * Select an icon
           */
          icon?: string | null;
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  companySection?: {
    title?: string | null;
    items?:
      | {
          /**
           * Select an icon
           */
          icon?: string | null;
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  resourcesSection?: {
    title?: string | null;
    items?:
      | {
          /**
           * Select an icon
           */
          icon?: string | null;
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  legalSection?: {
    title?: string | null;
    items?:
      | {
          /**
           * Select an icon
           */
          icon?: string | null;
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  socialSection?: {
    title?: string | null;
    items?:
      | {
          /**
           * Select an icon
           */
          icon?: string | null;
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  followUsSection?: {
    title?: string | null;
    socialLinks?:
      | {
          platform: 'facebook' | 'twitter' | 'instagram' | 'linkedin' | 'youtube' | 'tiktok';
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  copyrightText?: string | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure the chatbot welcome message, default response, and all questions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatbot".
 */
export interface Chatbot {
  id: number;
  welcomeMessage: {
    /**
     * The first message users see when opening the chatbot
     */
    text: string;
    /**
     * Quick action buttons shown in the welcome message. Use URL for links (blue) or leave empty to send as message (red)
     */
    quickOptions?:
      | {
          question: string;
          /**
           * Check to open a URL. Uncheck to send as message (Red Button)
           */
          typeMessage?: boolean | null;
          /**
           * Enter the URL to open. Examples: /productos, https://example.com
           */
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * This response is shown when no matching question is found
   */
  defaultResponse: {
    answer: string;
    /**
     * Buttons shown after the default response. With URL = link (blue), without URL = sends message (red)
     */
    followUpQuestions?:
      | {
          question: string;
          /**
           * Check to open a URL. Uncheck to send as message (Red Button)
           */
          typeMessage?: boolean | null;
          /**
           * Enter the URL to open. Examples: /productos, https://example.com
           */
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * All chatbot questions and their answers
   */
  questions?:
    | {
        /**
         * The main question users might ask
         */
        question: string;
        /**
         * Keywords that trigger this response
         */
        keywords?:
          | {
              keyword: string;
              id?: string | null;
            }[]
          | null;
        /**
         * The chatbot response. Use \n for line breaks
         */
        answer: string;
        /**
         * Suggested buttons shown after this answer. With URL = opens link (blue), without URL = sends message automatically (red)
         */
        followUpQuestions?:
          | {
              question: string;
              /**
               * Check to open a URL. Uncheck to send as message (Red Button)
               */
              typeMessage?: boolean | null;
              /**
               * Enter the URL to open. Examples: /productos, https://example.com
               */
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Category for organizing questions
         */
        category?: (number | null) | Category;
        /**
         * Higher number = higher priority. Used when multiple questions match
         */
        priority?: number | null;
        /**
         * Disable temporarily without deleting
         */
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Con esta opción se deshabilitara el chatbot en la página web para que no se muestre temporalmente o indefinidamente.
   */
  disabled?: boolean | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage promotional coupons and discounts with countdown timers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  /**
   * Show/hide the coupons section on the website
   */
  enabled?: boolean | null;
  /**
   * Main title for the coupons section
   */
  title?: string | null;
  /**
   * Subtitle or description for the coupons section
   */
  subtitle?: string | null;
  /**
   * Add promotional coupons (maximum 6)
   */
  coupons?:
    | {
        /**
         * Enable/disable this coupon
         */
        active?: boolean | null;
        /**
         * Unique coupon code (e.g., SAVE20, WELCOME10)
         */
        code: string;
        /**
         * Short descriptive title
         */
        title: string;
        /**
         * Detailed description of the offer
         */
        description?: string | null;
        discountType: 'percentage' | 'fixed' | 'shipping';
        /**
         * Percentage (e.g., 20 for 20%) or fixed amount (e.g., 100 for $100)
         */
        discountValue?: number | null;
        /**
         * Date and time when the coupon expires
         */
        expiryDate: string;
        /**
         * Minimum purchase amount required (optional)
         */
        minPurchase?: number | null;
        /**
         * Maximum number of times this coupon can be used (optional)
         */
        maxUses?: number | null;
        backgroundColor?: ('red' | 'blue' | 'green' | 'orange' | 'purple' | 'pink') | null;
        ctaText?: string | null;
        /**
         * Link when clicking the CTA button (e.g., /productos, /contacto)
         */
        ctaLink?: string | null;
        id?: string | null;
      }[]
    | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  productsMenu?:
    | T
    | {
        title?: T;
        showInNav?: T;
        hasDropdown?: T;
        directLink?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
            };
        items?:
          | T
          | {
              icon?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  servicesMenu?:
    | T
    | {
        title?: T;
        showInNav?: T;
        hasDropdown?: T;
        directLink?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
            };
        items?:
          | T
          | {
              icon?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  resourcesMenu?:
    | T
    | {
        title?: T;
        showInNav?: T;
        hasDropdown?: T;
        directLink?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
            };
        items?:
          | T
          | {
              icon?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  companyMenu?:
    | T
    | {
        title?: T;
        showInNav?: T;
        hasDropdown?: T;
        directLink?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
            };
        items?:
          | T
          | {
              icon?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  contactMenu?:
    | T
    | {
        title?: T;
        showInNav?: T;
        hasDropdown?: T;
        directLink?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
            };
        items?:
          | T
          | {
              icon?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  productSection?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              icon?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  companySection?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              icon?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  resourcesSection?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              icon?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  legalSection?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              icon?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  socialSection?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              icon?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  followUsSection?:
    | T
    | {
        title?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  copyrightText?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatbot_select".
 */
export interface ChatbotSelect<T extends boolean = true> {
  welcomeMessage?:
    | T
    | {
        text?: T;
        quickOptions?:
          | T
          | {
              question?: T;
              typeMessage?: T;
              url?: T;
              id?: T;
            };
      };
  defaultResponse?:
    | T
    | {
        answer?: T;
        followUpQuestions?:
          | T
          | {
              question?: T;
              typeMessage?: T;
              url?: T;
              id?: T;
            };
      };
  questions?:
    | T
    | {
        question?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        answer?: T;
        followUpQuestions?:
          | T
          | {
              question?: T;
              typeMessage?: T;
              url?: T;
              id?: T;
            };
        category?: T;
        priority?: T;
        active?: T;
        id?: T;
      };
  disabled?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  enabled?: T;
  title?: T;
  subtitle?: T;
  coupons?:
    | T
    | {
        active?: T;
        code?: T;
        title?: T;
        description?: T;
        discountType?: T;
        discountValue?: T;
        expiryDate?: T;
        minPurchase?: T;
        maxUses?: T;
        backgroundColor?: T;
        ctaText?: T;
        ctaLink?: T;
        id?: T;
      };
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    name?: string | null;
    format?: ('csv' | 'json') | null;
    limit?: number | null;
    page?: number | null;
    sort?: string | null;
    sortOrder?: ('asc' | 'desc') | null;
    drafts?: ('yes' | 'no') | null;
    selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
    fields?: string[] | null;
    collectionSlug: string;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    user?: string | null;
    userCollection?: string | null;
    exportsCollection?: string | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'products';
          value: number | Product;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'manuals';
          value: number | Manual;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'destructive' | 'success';
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonBlock".
 */
export interface ButtonBlock {
  align?: ('left' | 'center' | 'right' | 'full') | null;
  buttons?:
    | {
        title: string;
        url: string;
        style: 'default' | 'outline' | 'secondary' | 'link' | 'destructive' | 'ghost';
        effect?: ('none' | 'gooeyRight' | 'gooeyLeft' | 'ringHover' | 'shine' | 'shineHover') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'button';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QRCodeBlock".
 */
export interface QRCodeBlock {
  description: string;
  size: 'medium' | 'large';
  align?: ('left' | 'center' | 'right') | null;
  url: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'qr-code-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}